config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'welcome' => 'events#welcome'
  root "events#welcome"
  
  resources :users do
    member do
      get :activate
    end
    resources :events, except:[:new, :index] do
      resources :comments, only: [:destroy, :update, :create]
    end
    resources :movie_interests, except: [:index, :show]
    resources :ratings
    resources :commitments, only: [:destroy, :update, :create]
  end
  resources :friendships, only: [:destroy, :create] 
  resources :user_sessions, only: [:destroy, :new, :create]

  get 'all_events' => 'events#all_events', :as => :events
  # get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :hosted_events, class_name: "Event", foreign_key: 'host_id'   
  has_many :comments#, through: :events
  has_many :commitments
  has_many :movie_interests
  has_many :ratings

  mount_uploader :avatar, AvatarUploader

	has_many :friendships
	has_many :friends, through: :friendships

	has_many :inverse_friendships, class_name: "Friendship", foreign_key: "friend_id"
	has_many :inverse_friends, through: :inverse_friendships, source: :user
	
  authenticates_with_sorcery!
  validates :password, length: { minimum: 3 }, unless:  Proc.new { |a| a.password.blank? }
  validates :password, confirmation: true, unless:  Proc.new { |a| a.password.blank? }
  validates :password, presence: true, unless: Proc.new { |a| a.password_confirmation.blank? }

  validates :email, uniqueness: true
  validates :email, presence: true

  validates :first_name, presence: true
  validates :last_name, presence: true

  def is_friend?(user)
    if self.friendships.find_by(friend_id: user.id)
      self.friendships.find_by(friend_id: user.id).confirm
    else
      false
    end
  end

  def incoming_friendships
    Friendship.where(friend_id: self.id, confirm: false)
  end

  def self.search(query)
    where("first_name like ?", "%#{query}%") 
  end

  def pending_friendship?(current_user, user) 
    Friendship.exists?(friend_id: current_user.id, user_id: user.id) || Friendship.exists?(friend_id: user.id, user_id: current_user.id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_load_and_authorize_resource :only => [:new, :create, :activate]
  skip_before_filter :require_login, :only => [:new, :create, :activate]
  load_and_authorize_resource

  def activate
    if (@user = User.load_from_activation_token(params[:id]))
      @user.activate!
      redirect_to(root_path, :notice => 'User was successfully activated.')
    else
      not_authenticated
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.first_name.capitalize!
    @user.last_name.capitalize!
    if @user.save

      redirect_to root_path, notice: "Success! Please check confirmation email"
    else
      flash.now[:alert] = "An error occurred!"
      render 'events/welcome'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.hosted_events.each do |event|
      event.commitments.destroy_all
      event.comments.destroy_all
    end
    @user.hosted_events.destroy_all
    @user.commitments.destroy_all
    @user.comments.destroy_all
    @user.movie_interests.destroy_all
    @user.ratings.destroy_all
    @user.friendships.destroy_all
    Friendship.where(friend_id: @user.id).destroy_all
    @user.destroy
    redirect_to root_path, notice: "User deleted :("
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to user_path(@user), notice: "Changes successful"
    else
      flash.now[:alert] = "An error occurred!"
      render 'edit'
    end
  end

  def index
    if current_user
      @users = if params[:user_search]
        User.where("LOWER(first_name) LIKE LOWER(?) OR LOWER(last_name) LIKE LOWER(?)", "%#{params[:user_search]}%", "%#{params[:user_search]}%").select{|u| !u.is_friend?(current_user)}.sort{|x,y| x.first_name <=> y.first_name}
      else
        User.select{|u| !u.is_friend?(current_user) && u.id != current_user.id}.sort{|x,y| x.first_name <=> y.first_name}
      end
    end

    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    @user = User.find(params[:id])
    @attending = @user.commitments.order(created_at: :desc).page(params[:attending_page]).per(4)
    @hosting = @user.hosted_events.order(created_at: :desc).page(params[:hosting_page]).per(4)
    @ratings = @user.ratings.order(created_at: :desc).page(params[:ratings_page]).per(3)


    if current_user
      if params[:friend_search]
        @friends = User.where("LOWER(first_name) LIKE LOWER(?) OR LOWER(last_name) LIKE LOWER(?)", "%#{params[:friend_search]}%", "%#{params[:friend_search]}%").select{|u| u.is_friend?(@user)}.sort{|x,y| x.first_name <=> y.first_name}
        @friends = Kaminari.paginate_array(@friends).page(params[:friends_page]).per(6)
      else
        @friends = @user.friendships.sort{|x,y| x.friend.first_name <=> y.friend.first_name}
        @friends = Kaminari.paginate_array(@friends).page(params[:friends_page]).per(6)
      end
    end

    @user_id = @user.id
    gon.user_id = @user.id

    if @user.ratings.any?
      totalScore = (@user.ratings.all.inject(0){|sum, rating| sum + rating.user_score}).to_f
      maxScore = ((@user.ratings.all.count) * 5).to_f
      averageScore = ((totalScore / maxScore).to_f * 100.0).round(1)
      gon.average = ["Average Movie Rating", averageScore]

      # Favourite Genres
      def pieData(dataList)
        dataHash = dataList.each_with_object(Hash.new(0)) { |word,counts| counts[word] += 1 }
        dataArray = dataHash.map{|key, value| [key, value]}
        sortedArray = dataArray.sort!{|x,y| y[1] <=> x[1]}
        if sortedArray.length < 5
          return sortedArray[0..sortedArray.length]
        else
          return sortedArray[0..4] << ["Other", sortedArray[5..-1].inject(0){|sum, x| sum + x[1]}]
        end
      end

      genreList = @user.ratings.where('user_score >= 4').map{|rating| [] << rating.genres.split(", ").flatten}.flatten
      gon.genres = pieData(genreList);

      actorsList = @user.ratings.where('user_score >= 4').map{|rating| [] << rating.actors.split(", ").flatten}.flatten
      gon.actors = pieData(actorsList);

      directorsList = @user.ratings.where('user_score >= 4').map{|rating| [] << rating.directors.split(", ").flatten}.flatten
      gon.directors = pieData(directorsList);
    end

    respond_to do |format|
      format.html
      format.js
    end

  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :avatar, :bio, :hometown)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_current_friends.html.erb
<div class="section-heading">
  <b>Friends&nbsp;(<%= @user.friendships.where(confirm: true).count %>)</b>
</div><br>
<%= form_tag @user_path, method: :get, authentication: false, id: 'friend-search-form' do %>
  <%= text_field_tag :friend_search, params[:friend_search], placeholder: "Search Friends" %>
  <%= submit_tag "Search", class:"button tiny" %>
<% end %>
<% unless params[:friend_search] %>
  <% @friends.each do |friendship| %>
    <% if friendship.confirm %>
      <div class="friend-container">
        <div class="top-friend-panel">
          <%= link_to image_tag(friendship.friend.avatar, id:"friend-avatar"), user_path(friendship.friend_id)%>
        </div>
        <div class="mid-friend-panel">
          <div id="friend-name">
            <p><%= link_to friendship.friend.first_name + " " + friendship.friend.last_name, user_path(friendship.friend), class: "small-marker-caps" %></p>
            <br>
          </div>
          <div id="friend-details">
            <% friendCount = 0 %>
            <% friendship.friend.friendships.each do |friendship2| %>
              <% if friendship2.confirm %>
                <% friendCount += 1 %>
              <% end %>
            <% end %>
                
            <p class="small-caps">Reviews: <%= friendship.friend.ratings.length %> | Friends: <%= friendCount %></p>
          </div>
            <% if @user == current_user %> 
            <br>
            <center><%= link_to "Remove Friend", friendship_path(friendship, friend_id: friendship.friend.id), data: { confirm: 'Are you sure?' }, class:"small-caps", id:"remove-friend", method: :delete %></center>
            <% end %>  
        </div>

      </div>
    <% end %>
  <% end %>
<% else %>
  <% if @friends != []%>
    <% @friends.each do |friendship| %>
      <div class="friend-container">
        <div class="top-friend-panel">
          <%= link_to image_tag(friendship.avatar, id:"friend-avatar"), user_path(friendship)%>
        </div>
        <div class="mid-friend-panel">
          <div id="friend-name">
            <p><%= link_to friendship.first_name + " " + friendship.last_name, user_path(friendship), class: "small-marker-caps" %>
            <% if @user == current_user %>
              <%= link_to "(-)", friendship_path(@user.friendships.find_by(friend_id: friendship.id), friend_id: friendship.id), data: { confirm: 'Are you sure?' }, class:"small-caps", id:"remove-friend", method: :delete %></p>
            <% end %>  
            <br>
          </div>
          <div id="friend-details">          
            <% friendCount = 0 %>
            <% friendship.friendships.each do |friendship2| %>
              <% if friendship2.confirm %>
                <% friendCount += 1 %>
              <% end %>
            <% end %>
              <p class="medium-caps"><%= friendship.bio %></p>
              <p class="small-caps">Reviews: <%= friendship.ratings.length %> | Friends: <%= friendCount %></p>
          </div>
        </div>
      </div>
    <% end %>
  <% else %>
    <p>No results found</p>
  <% end %>
  <%= link_to "Back to all friends", @user_path, id: "back-to-friends" %>
<% end %>
<center>
<div id="friends-pagination">
  <%= paginate @friends, :remote => true, :param_name => "friends_page", params: {ratings_page: params[:ratings_page]} %>
</div>
</center>

app/views/users/_form.html.erb
<p>Profile</p>
<p class="small-caps remove-lh">Change your basic account settings and information.</p>

<hr>

<%= form_for @user, :html => {:multipart => true} do |f|%>

  <%= render 'user_errors' %>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>      
  <div class="field">
    <%= f.label :avatar %>
    <%= f.file_field :avatar %>
  </div>
  <div class="field">
    <%= f.label :bio %>
    <%= f.text_area :bio, :size => "25x3", maxlength: 150, class: "message" %>
  </div>
  <div class="countdown"></div>
  <div class="field">
    <%= f.label :hometown %>
    <%= f.text_field :hometown %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit class: "button expand" %>
  </div>
<% end %>

app/views/users/_hosted_events.html.erb
<div class="hosting-event-container">
	<% unless @hosting.empty? %>
	  	<% @hosting.each do |event| %>
		  	<% if event.not_passed %>
		  	<% movie = Movie.find_movie(event.rt_id) %>
					<div class="profile-event-container">
						<div class="event-banner" style="background-image: url(<%= movie.poster.gsub("tmb", "det") %>)">
						</div>
						<div class="host-profile-event-title">
							<center><b><%= link_to user_event_path(@user, event) do %>
								<%= event.title %> in <%= ((event.time - Time.now)/86400).ceil %> Days</b></center>
								<% end %>
						</div>
						<div class="profile-event-details">
							<% if event.attendees != [] %>
								<% event.attendees.each do |a| %>
								<% puts "user id: " + a.id.to_s + ", event id: " + event.id.to_s %>
									<%= image_tag("#{a.avatar_url(:thumb)}", id: "attendee-thumb") %>
									<span class="guests-total medium-caps">
										<%= event.commitments.where(user: a).first.guests %>
									</span>
								<% end %>
								<% else %>
									<p>You have no guests confirmed</p>
							<% end %>
						</div>
					</div>
		 	 <% end %>
	 	<% end %>
		<div id="hosting-pagination"><center><%= paginate @hosting, :remote => true, :param_name => "hosting_page" %></center></div>

		<div class="small-caps"><center><%= page_entries_info @hosting %></center></div>
	<% else %>
		<p class="no-data-filler">
			<% if @user == current_user %>
					You are not currently hosting any events
			<% else %>
				<%= @user.first_name %> has no hosted events currently
			<% end %>
		</p>
	<% end %>
</div>

app/views/users/_password_form.html.erb
<p>Password</p>
<p class="small-caps remove-lh">Change your email or password.</p>

<hr>

<%= form_for @user, :html => {:multipart => true} do |f|%>

  <%= render 'user_errors' %>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password, "New Password" %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirm New Password" %>
    <%= f.password_field :password_confirmation %>
  </div>   
  <div class="actions">
    <%= f.submit "Update Password", class: "button expand" %>
  </div>
<% end %>

app/views/users/_ratings.html.erb
<% unless @ratings.empty? %>
	<% @ratings.each do |rating| %>
	<p>
		<% if rating.id != nil %>
		<div class="review-entry-container">
	        <div class="title-bar"><%= Movie.find_movie(rating.rt_id).title %></div>
	    
	        <div class="review-content">"<%= rating.review %>"</div>

	        <% width = ((rating.user_score.to_i/5.to_f) * 100.to_i).to_i %>
			<div class="rating_bar">
				<div class="rating" style= "width:<%= width %>%"></div>
			</div><br/>
			<div class="edit-review-bar small-caps">
				<span><%= rating.created_at %><br/></span>
				<% if current_user == @user %>
				<span class="edit-review-entry">
					<%= link_to "Edit", edit_user_rating_path(@user, rating), class:"small-caps"%> | 
					<%= link_to "Remove", user_rating_path(@user, rating), data: { confirm: 'Are you sure?' }, class:"small-caps", method: :delete %>
					</span>
				<% end %>
			</div>
		</div>
		<% end %>
	</p>
	<% end %>
	<div id="ratings-pagination"><center><%= paginate @ratings, :remote => true, :param_name => "ratings_page", params: {friends_page: params[:friends_page]} %></center></div>

	<div class="small-caps"><center><%= page_entries_info @ratings %></center></div>
<% else %>
	<p class="no-data-filler">
		<% if @user == current_user %>
			You do not have any reviews currently
		<% else %>
			<%= @user.first_name %> does not have any reviews currently
		<% end %>
	</p>
<% end %>

app/views/users/_user_errors.html.erb
<% if @user.errors.any? %>
	<div class="error_messages">
	  <h5>Form is invalid</h5>
	  <ul>
	    <% for message in @user.errors.full_messages %>
	      <li class="error-li"><%= message %></li>
	    <% end %>
	  </ul>
	</div>
<% end %>

app/views/users/_users.html.erb
<% if @users %>
	<% @users.each do |user| %>
		<% unless current_user.pending_friendship?(current_user, user) %>
			<%= link_to(friendships_path(friend_id: user.id), method: :post, :remote => true) do %>
				<% unless user == current_user %>
					<div class="user-container">
						<%= image_tag user.avatar, class: "user-avatar" %>
					  <div class="user-text-container">
					  	<%= user.first_name %> <%= user.last_name %>
					  	<% if user.hometown && user.hometown != "" %>
				  		 | <%= user.hometown %>
				  		<% end %>
					  </div>
					  <div class="user-add">
					  	<i class="fa fa-plus-circle"> Add Friend</i>
					  </div>	
					</div>
				<% end %>
			<% end %>
		<% else %>
			<% unless user == current_user %>
				<div class="user-container-pending">
					<%= image_tag user.avatar, class: "user-avatar" %>
				  <div class="user-text-container">
				  	<%= user.first_name %> <%= user.last_name %>
				  	<% if user.hometown && user.hometown != "" %>
				  		 | <%= user.hometown %>
				  	<% end %>
				  </div>
				  <div class="user-add">
						<i class="fa fa-clock-o"> Pending</i>
				  </div>	
				</div>
			<% end %>
		<% end %>
	<% end %>
<% end %>
<% if params[:user_search] %>
	<% if @users == [] %>
		<p>No Results Found</p>
	<% end %>
	<%= link_to "Back to all users", users_path, remote: true %>
<% end %>

app/views/users/_wishlist.html.erb
<% unless @user.movie_interests.empty? %>
	<ul id="featured1 inline-list" data-orbit>
		<% count = 0 %>
	  	<li>
			<% @user.movie_interests.each do |movie| %>
				<% count += 1 %>
				<div class="car-img-container">
					<img class= "car-img" src="<%= Movie.find_movie(movie.rt_id).poster %>" style="float:left; padding-right:5px;" />
					<% if current_user.id == @user.id %>
						<%= link_to "Remove", user_movie_interest_path(@user,movie), data: { confirm: 'Are you sure?' }, method: :delete, class:"small-caps" %>
					<% end %>
				</div>
					<% if count % 3 == 0 %>
						</li>
						<li>
				<% end %> 
		 	<% end %>
		</li>
	</ul>
<% else %>
	<p id="no-data-filler-wish">No movies added to wishlist yet</p>
<% end %>	

app/views/users/edit.html.erb
<div class="edit-container">
	<div class="row">
		<div class="large-4 medium-4 small-12 columns">

			<div id="edit-avatar-section">
				<div id="edit-avatar-panel">
					<%= image_tag @user.avatar_url(:profile), id: 'edit-profile-image'%>
				</div>
				<div id="edit-avatar-details">
					<br>
					<b><%=@user.first_name%> <%=@user.last_name%></b>
				</div>
			</div>
			<dl class="tabs vertical edit-panels" data-tab>
			  <dd class="active edit-effects"><a href="#edit-panel1" class="top-edit-panel">Profile</a></dd>
			  <dd class="edit-effects"><a href="#edit-panel2">Password</a></dd>
			  <dd class="edit-effects"><a href="#edit-panel3" class="bottom-edit-panel">Delete Account</a></dd>
			</dl>
		</div>
		<div class="large-8 medium-8 small-12 columns">
			<div class="tabs-content vertical">
			  <div class="content active" id="edit-panel1">
			    <%= render 'form' %>
			  </div>
			  <div class="content" id="edit-panel2">
			    <%= render 'password_form' %> 
			  </div>
			  <div class="content" id="edit-panel3">
				<%= render 'delete_form' %>
			  </div>
			</div>
		</div>
	</div>
</div>

app/views/users/index.html.erb
<div class="form-container">
	<div class="row">
		<div class="small-8 small-centered columns">
			<div class="friend-page form-styling">
				<h3>Invite Friends</h3><br /><br />

				<%= form_tag(users_path, :method => "get", id: "search-form") do %>
					<%= text_field_tag :user_search, params[:user_search], placeholder: "Search by first or last name" %>
					<%= submit_tag "Search", :name => nil, class: "button tiny" %>
				<% end %>
				
				<hr />

				<div id="friend-list">
					<%= render :partial => "users" %>
				</div>
			</div>
		</div> 
	</div>
</div>

app/views/users/index.js.erb
$('#friend-list').html("<%= j render :partial => 'users' %>");
$('#user_search').val("");

app/views/users/new.html.erb
<h1>Sign up</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<div class="container">
	<div class="row" id="chart-row">
		<%= render :partial => "chart_toggle" %>
	</div>
	<div class="row" id="status-row">
		<div class="large-3 medium-3 small-12 columns" id="status-space">
			<%= image_tag @user.avatar_url(:profile), id: 'profile-image'%>
			<div id="profile-info">	
				<p class="profile-name"><b><%=@user.first_name%> <%=@user.last_name%></b></p>
				<div class="profile-record">
					<% if (@user.bio == nil || @user.bio == "") && current_user.id == @user.id  %>
						<p><%= link_to "Add a bio", edit_user_path(@user) %></p>
					<% elsif @user.bio == nil || @user.bio == ""%>
						<p>No record for bio</p>
					<% else %>
						<p><%= @user.bio %></p>
					<% end %>
					<% if (@user.hometown == nil || @user.hometown == "") && current_user.id == @user.id %>
						<p><%= link_to "Add a location", edit_user_path(@user) %></p>
					<% elsif @user.hometown == nil || @user.hometown == ""%>	
						<p>No record for location</p>
					<% else %>
						<div class="location-card"><span class="location-marker"><%= image_tag 'location_marker.png', size:"25" %></span><span class="hometown-location medium-caps"><%= @user.hometown %></span></div>
					<% end %>
				</div><br>
	      <p class="small-caps">Joined on: <%=@user.created_at%></p>
			</div>
			<div class="popr-mascot-position1"><%= image_tag("popr_mascot1.png") %></div>
		</div>
		<div class="large-7 medium-7 small-7 columns" id="status-details">
			<dl class="tabs" data-tab>
			  <dd class="active animate">
			  	<a href="#p1" id="left-tab">HOSTING</a>
			  	<% count_host = 0 %>
			  	<% @user.hosted_events.each do |event| %>
						<% if event.not_passed %>
							<% count_host += 1%>
						<% end %>
			  	<% end %>
					<span class="profile-counts"><center><%= count_host %></center></span>
			  </dd>
			  <dd class="animate">
			  	<a href="#p2" id="center-tab">ATTENDING</a>
			  	<% count_attend = 0 %>
			  	<% @user.commitments.each do |commitment| %>
						<% if commitment.event.not_passed %>
							<% count_attend += 1%>
						<% end %>
			  	<% end %>
					<span class="profile-counts"><center><%= count_attend %></center></span>
			  </dd>
			  <dd class="animate">
			  	<a href="#p3" id="center-tab">FRIENDS</a>
					<span class="profile-counts"><center><%= @user.friendships.where(confirm: true).count %></center></span>
			  </dd>
			  <dd class="animate">
			  	<a href="#p4" id="center-tab">REVIEWS</a>
					<span class="profile-counts"><center><%= @user.ratings.length %></center></span>
			  </dd>
			  <dd class="animate">
			  	<a href="#p5" id="right-tab">WISHLIST</a>
			  	<% count_wish = 0 %>
			  	<% @user.movie_interests.each do |movie_interest| %>
			  		<% if movie_interest.wished %>
			  			<% count_wish += 1 %>
			  		<% end %>
			  	<% end %>
			  	<span class="profile-counts"><center><%= count_wish %></center></span>
			  </dd>
			</dl>
		</div>
		<div class="large-2 medium-2 small-12 columns" id="edit-profile-btn">
			<% if current_user == @user %>
				<%= link_to "Edit Profile", edit_user_path(@user), class:"button tiny"%>
      <% end %>
		</div>
	</div>

	<div class="row" id="user-content-row">
		<div class="large-9 medium-9 small-12 columns" id="user-tab-content">
			<div class="tabs-content">
				<div class="content active" id="p1">
				<div class="section-heading"><b>Hosted Events</b></div>
					<div class="host-list">
						<%= render :partial => "hosted_events" %>
					</div>
				</div>
				<div class="content" id="p2">
					<div class="section-heading"><b>Joined Events</b></div>
					<div id="attending-list">
						<%= render :partial => "attending_events" %>
					</div>
				</div>
				<div class="content" id="p3">
					<div id="current-friends">
    				<%= render :partial => "current_friends" %>
    			</div>
  			</div>
			
				<div class="content" id="p4">
					<div class="section-heading"><b>Reviews <%= link_to "(view all)", user_ratings_path(@user), class:"small-caps"%></b></div><br/>
					<div id="review-list">
						<%= render :partial => "ratings" %>
					</div>
				</div>
				<div class="content" id="p5">
					<div class="section-heading"><b>Wishlist</b></div>
					<div id="wish-section">
						<%= render :partial => "wishlist" %>
					</div>	
				</div>
			</div>
		</div>
	</div>
</div>

	

<script>

	var chart = c3.generate({
		bindto: '#chart',
		data: {
			columns: gon.genres,
			type: 'donut',
			hide: true,
      hide: ['Other']
    },
    legend: {
    	position: 'inset',
    	inset: {
    		anchor: 'bottom-right',
    		x:10,
    		y:100
    	}
    },
    donut: {
      title: "Favourite Genres",
      width: 80
    }
  });

	var chart2 = c3.generate({
		bindto: '#chart2',
		data: {
			columns: gon.actors,
			type: 'donut',
			hide: true,
      hide: ['Other']
    },
    legend: {
    	position: 'inset',
    	inset: {
    		anchor: 'bottom-right',
    		x:10,
    		y:100
    	}
    },
    donut: {
      title: "Favourite Actors",
      width: 80,
    }
  });

	var chart3 = c3.generate({
		bindto: '#chart3',
		data: {
			columns: gon.directors,
			type: 'donut',
			hide: true,
      hide: ['Other']
    },
    legend: {
    	position: 'inset',
    	inset: {
    		anchor: 'bottom-right',
    		x:10,
    		y:100
    	}
    },
    donut: {
      title: "Favourite Directors",
      width: 80
    }
  });

	var chart4 = c3.generate({
		bindto: '#chart4',
    data: {
      columns: [
      gon.average
      ],
      type: 'gauge',
    },
    color: {
      pattern: ['#FF0000', '#F97600', '#F6C600', '#60B044'], // the four color levels for the percentage values.
      threshold: {
//            unit: 'value', // percentage is default
//            max: 200, // 100 is default
values: [30, 60, 75, 100]
}
},
});


</script>

app/views/users/show.js.erb
$('#attending-list').html("<%= j render :partial => 'attending_events' %>");
$('#attending-pagination').html("<center><%= j paginate @attending, :remote => true, :param_name => 'attending_page'  %><center>");
$('#host-list').html("<%= j render :partial => 'hosted_events' %>");
$('#host-pagination').html("<center><%= j paginate @hosting, :remote => true, :param_name => 'hosting_page'  %><center>");
$('#review-list').html("<%= j render :partial => 'ratings' %>");
$('#ratings-pagination').html("<center><%= j paginate @ratings, :remote => true, :param_name => 'ratings_page', params: {friends_page: params[:friends_page]} %></center>"); 
$('#current-friends').html("<%= j render :partial => 'current_friends' %>");
$('#friends-pagination').html("<center><%= j paginate @friends, :remote => true, :param_name => 'friends_page', params: {ratings_page: params[:ratings_page]} %></center>");