config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'welcome' => 'events#welcome'
  root "events#welcome"
  
  resources :users do
    member do
      get :activate
    end
    resources :events, except:[:new, :index] do
      resources :comments, only: [:destroy, :update, :create]
    end
    resources :movie_interests, except: [:index, :show]
    resources :ratings
    resources :commitments, only: [:destroy, :update, :create]
  end
  resources :friendships, only: [:destroy, :create] 
  resources :user_sessions, only: [:destroy, :new, :create]

  get 'all_events' => 'events#all_events', :as => :events
  # get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_one :movie_interest
  belongs_to :host, class_name: "User"
  has_many :comments
  has_many :commitments

  validates :title, presence: true
  validates :address, presence: true
  validate :ensure_dates
  
  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  # Function to verify if requested party size of commitment being made
  # falls within the event capacity set by the host.

  def is_available?(party_size)
    confirmed = self.commitments.sum(:party_size)
    self.capacity - (confirmed + party_size) >= 0
  end

  def attendees
    @attendees =[]
    self.commitments.each {|c| @attendees << c.user if c.id}
    @attendees
  end


  def ensure_dates
    if(time < Time.now)
      errors.add(:time, "can't start in the past")
    end
  end

  def date_details
    self.time.strftime("%A, %B %e, %Y - %l:%M %P ")
  end

  def not_passed
    self.time >= Time.now
  end

  def time_left 
    ((self.time.Date - Time.now)/86400).ceil
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :set_event, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  skip_authorize_resource :only => :welcome

  def welcome
    @user = User.new
    if current_user
      redirect_to events_path
    end
  end

  def all_events

    @events = if params[:search_location]
      Event.near(params[:search_location], 20, units: :km).select{|event|event.host.is_friend?(current_user) && event.not_passed}
    elsif params[:latitude] && params[:longitude]
      Event.near([params[:latitude], params[:longitude]], 20, units: :km).select{|event|event.host.is_friend?(current_user) && event.not_passed}
    else
      Event.all.select{|event| event.host.is_friend?(current_user) && event.not_passed} 
    end
    

    # Return current position to the map and filter by friends
    c_position = [params[:latitude], params[:longitude]]

    @current_position = if params[:search_location]
        Event.near(params[:search_location], 20, units: :km)
      elsif params[:latitude] && params[:longitude] 
        Event.near(c_position, 10, units: :km)
      else
        Event.all
      end

    @friend_check = @current_position.select{|event| event.host.is_friend?(current_user) && event.not_passed}
    @nearby_coords = @friend_check.map {|event| {latitude: event.latitude.to_f, longitude: event.longitude.to_f, title: event.title, poster: Movie.find_movie(event.rt_id).poster, commitment: event.commitments.sum(:party_size).to_s, capacity: event.capacity.to_s, address: event.address, time: event.time.strftime("%B %d, %Y - %l:%M %p"), description: event.description}}
    respond_to do |format|
      format.html
      format.js
    end

  end

  def show
    @commitment = current_user.commitments.find_or_initialize_by(event: @event)
    @movie = Movie.find_movie(@event.rt_id)
    @comment = @event.comments.build
    @EventComments = @event.comments.all
  end

  def create
    @event = Event.new(event_params)
    @event.host = current_user
    # @user = User.find(params[:user_id])
    if @event.save
      redirect_to user_event_path(@event.host, @event), notice: "Event successfully created!"
    else
      message_string = []
      @event.errors.full_messages.each do |message|
        message_string << message
      end
      redirect_to :back, alert: ("Event: " + message_string.join(", ").capitalize)
    end
  end

  def edit
    @user = User.find(params[:user_id])
  end

  def update
    @user = User.find(params[:user_id])
    if @event.update_attributes(event_params) 
      redirect_to user_event_path(@event.host, @event), notice: "Event successfully modified!"
    else
      flash.now[:alert] = "An error occurred!"
      render 'edit'
    end
  end

  def destroy
    @event.commitments.destroy_all
    @event.comments.destroy_all
    @event.destroy
    redirect_to root_url, notice: "Event succesfully deleted."
  end

  private
  def event_params
    params.require(:event).permit(:time, :address, :longitude, :latitude, :description, :title, :capacity, :rt_id)
  end

  def set_event
    # This setter properly displays only the events which are hosted by user whose ID
    # is in the params. e.g. /users/1/events/12 ; Event 12 is hosted by User 1.
    # This query will not allow getting to Event 12 through User 2, i.e.
    # /users/2/events/12 .
    @event = User.find(params[:user_id]).hosted_events.where(events: {id: params[:id]}).first  
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_comment_form_errors.html.erb
<% if @comment.errors.any? %>
	<div id="error_explanation">
		<h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

		<ul>
			<% @comment.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/events/_comments.html.erb
<% @event.comments.each do |comment| %>
  <% if comment.id %>
    <div class="comment-panel">
      <div class="large-2 columns">
        <div class="comment-user">
          <% if comment.user == @event.host %>
            <%= image_tag @event.host.avatar_url(:thumb), id: "avatar-thumb" %>
          <% else %>  
            <%= image_tag comment.user.avatar_url(:thumb), id: "avatar-thumb" %>
          <% end %>
            <%= comment.user.first_name %>
        </div>
      </div>
      <div class="comment large-10 columns">
        <strong>"<%= comment.content %>"</strong><br />
        <div class="comment-date">
          - Posted on <%= comment.pretty_date %>
          <% if current_user == comment.user %>
             | <%= link_to "Delete", user_event_comment_path(@event.host, @event, comment), method: :delete, data: { confirm: 'Are you sure?' }, remote: true %>
          <% end %>
        </div>
      </div>
    </div>       
  <% end %>  
<% end %>

app/views/events/_edit_form.html.erb
<%= form_for([@user, @event]) do |f|%>

  <%= render 'event_errors' %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, maxlength: 40, class: "message-title" %>
  </div>
  <div class="countdown-title"></div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, rows: "3", id: "new-event-description", maxlength: 140, class: "message-description" %>
  </div>
  <div class="countdown-description"></div> 
    
  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address, size: "90" %>
  </div>

  <div class="field">
    <%= f.label :time %>
    <%= f.datetime_select :time, :minute_step => 5, :start_year => Date.today.year %>
  </div>

  <div class="field">
    <%= f.label :capacity %>
    <%= f.number_field :capacity, {min: 1, value: 1} %>
  </div>

  <div class="actions">
    <%= f.submit class: "button expand" %>
  </div>
<% end %>

app/views/events/_event.html.erb
<section class="event">
	<% if @events != [] %>
	<% @events.each do |event| %>
		<% movie = Movie.find_movie(event.rt_id) %>
		<div id="event-wrapper">
			<div id="event-poster" style="background-image: url(<%= movie.poster %>);"></div>
			<div id="event-content">
				<div class="row">
					<div class="large-12 columns" id="event-info">
						<span id="event-title">
							<p><b><%= link_to(event.title, user_event_path(event.host_id, event.id)) %>&nbsp;(<%=event.commitments.sum(:party_size)%>/<%= event.capacity%>)</b></p>
							<p class="small-caps"><%= event.time.strftime("%A, %d %b %Y %l:%M %p") %></p>
							<p class="small-caps"><%= event.address %></p>
							<p class="small-caps"><i><%= event.description %></i></p>
						</span>
						<% if event.attendees.include?(current_user) %>
							<b class="small-caps" style="color: #BD1E2C;">You're attending!</b>
						<% else %>
							<b class="small-caps"><%= link_to("Join Now!", user_event_path(event.host_id, event.id)) %></b>
						<% end %>
					</div>
					<div class="large-12 columns" id="event-attendance">
						<p class="small-caps">Who else is attending?</p>
						<div class = row>
							<div class="user-event-container">
								<div id="guest-container">
									<% guest_count = 0 %>
									<% event.attendees.each do |a| %>
										<% if guest_count < 2 %>	
											<% guest_count += 1%>
											<%= image_tag("#{a.avatar_url(:thumb)}", class:"guest-thumb") %>
										<% elsif guest_count == 2 %>
											<% guest_count += 1%>
											<%= link_to image_tag("extra_user.png", class:"guest-thumb"), user_event_path(event.host_id, event.id)  %>
										<% end %>
									<% end %>
								</div>
								<div id="host-container">
									<%= image_tag("popcorn.png", class:"icon") %>
									<%= image_tag("#{event.host.avatar.thumb}", id:"host-thumb", class:"hostImage") %>
								</div>
							</div>	
						</div>			
					</div>
				</div>
			</div>	
		</div>
	<% end %>
	<% else %>
		<div id="events-filler">
			<% if params[:search_location] %>
				<p>No Events at Searched Location</p>
			<% else %>
				<p>No Upcoming Events</p>
			<% end %>
		</div>
	<% end %>	
</section>

app/views/events/_event_details.html.erb
<h3><%= @event.title %></h3><br />

<h4>Hosted by: 
  <%= link_to user_path(@event.host) do %>
    <%= image_tag @event.host.avatar_url(:thumb), id: "avatar-thumb" %> <%= @event.host.first_name %> <%= @event.host.last_name %>
  <% end %>
</h4><br />

<% unless @event.description.empty? %>
  <h5>"<%= @event.description %>"</h5><br />
<% end %>

<h5>
  <i><strong><%=@event.date_details%></strong></i>
</h5>

<h5><%= @event.address %></h5>  

<% if !@event.not_passed %>
  <b><h5>This event has passed!</h5></b>
<% end %> 

<div class="panel">
  <p><strong>Poprs:</strong> <%= @event.commitments.sum(:party_size) %> / <%= @event.capacity %></p>
  <% if @event.commitments %>
    <ul class="small-block-grid-3 attendees-container">
      <% unless @event.commitments.empty? %>
        <% @event.commitments.each do |commitment| %>
          <% if commitment.id %>
            <div class="attendees">
              <li>
                <p>
                  <%= link_to user_path(commitment.user) do %>
                    <%= commitment.user.first_name %>
                    <i><%= commitment.guests %></i>
                    <%= image_tag commitment.user.avatar_url(:thumb), id: "avatar-thumb" %>
                  <% end %>
                </p>
              </li>
            </div>
          <% end %>  
        <% end %>
      <% else %>
        <div class="attendees">
          <p id="empty-commitments">No Poprs Yet!</p>
        </div>
      <% end %>
    </ul>
  <% end %> 
</div>       

app/views/events/_event_errors.html.erb
<% if @event.errors.any? %>
	<div class="error_messages">
	  <h5>Form is invalid</h5>
	  <ul>
	    <% for message in @event.errors.full_messages %>
	      <li class="error-li"><%= message %></li>
	    <% end %>
	  </ul>
	</div>
<% end %>

app/views/events/_form.html.erb
<%= form_for([@user, @event], url: user_events_path(user_id: current_user), html: {method: :post}) do |f|%>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, maxlength: 40, class: "message-title" %>
  </div>
  <div class="countdown-title"></div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, rows: "3", id: "new-event-description", maxlength: 140, class: "message-description" %>
  </div>
  <div class="countdown-description"></div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address, size: "90" %>
  </div>

  <div class="field">
    <%= f.label :time %>
    <%= f.datetime_select :time, :minute_step => 5, :start_year => Date.today.year %>
  </div>

  <div class="field">
    <%= f.label :capacity %>
    <%= f.number_field :capacity, {min: 1, value: 1} %>
  </div>

  <div class="input-container">
    <%= f.hidden_field :rt_id, value: "" %>
  </div> 

  <div class="actions">
    <%= f.submit class: "button expand" %>
  </div>
  
<% end %>

app/views/events/_map.html.erb
<%= content_tag "div", "map-canvas", id: 'map-canvas' , data: {latitude: 0.0, longitude: 0.0, coords: @nearby_coords} %>

app/views/events/_movie_details.html.erb
<%= image_tag @movie.poster, id: "event-page-poster" %>
<h3><%= @movie.title %> (<%= @movie.year %>)</h3><br />
<p>
  <b>Critics Rating:</b> 
  <% if @movie.rating[0].include?("Fresh") %>
    <img class="event-critics-score" src="http://d3biamo577v4eu.cloudfront.net/static/images/trademark/fresh.png"> 
  <% elsif @movie.rating[0].include?("Rotten") %>
    <img class="event-critics-score" src="http://d3biamo577v4eu.cloudfront.net/static/images/trademark/rotten.png">
  <% else %>
    <img class="event-critics-score" src="http://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Icon-round-Question_mark.svg/200px-Icon-round-Question_mark.svg.png"> 
  <% end %>
  <b><%= @movie.rating[1] >= 0 ? @movie.rating[1] : "-" %>%</b> 
</p> 
<p><b>Cast:</b> 
  <% @movie.cast.each do |actor| %>
   <i><%= actor["name"] %> /</i> 
  <% end %>
</p>
<% if current_user == @event.host %>
  <%= link_to "Edit Event", edit_user_event_path(@event.host, @event), class: "edit-buttons" %> | 
  <%= link_to "Cancel Event", user_event_path(@event.host, @event), data: { confirm: 'Are you sure you would like to cancel the event?' }, method: :delete, class: "edit-buttons" %>
<% end %>

app/views/events/all_events.html.erb
<div class="page-container">
	<div id="row">
		<div class="large-8 medium-12 small-12 columns" id="map-container">	
			<%= render 'map' %>
		</div>
		<div class= "large-4 medium-12 small-12 columns" id="side-bar" style="overflow: scroll">
			<div id="all-event-container">
				<div class="wrapper">
					<center>
					<%= form_tag(events_path, :method => "get", id: "event-search-form") do %>
						<%= text_field_tag :search_location, params[:search_location], placeholder: "Search events by location" %>
						<%= submit_tag "Search", :name => nil, class: "button tiny", id:"event-search-submit" %>
						<%= link_to "Near Me", events_path, id:"near-me-button", class:"button tiny" %>
					<% end %>
					</center>
					<!-- <center><a id="btnToggle" class="button tiny round">More Filters</a></center> -->
					<div id="slidingDiv" style="display:none;">
						Genres 
						<hr>
					</div>
				</div>
				<div class="event-listing">
				<div class="spinner">
				  <div class="bounce1"></div>
				  <div class="bounce2"></div>
				  <div class="bounce3"></div>
				</div>
				</div>
			</div>
		</div>

	</div>
</div>

<div id="footer-image">
	<%= image_tag('popr_footer.png') %>
</div>

app/views/events/all_events.js.erb
var coords = <%= @nearby_coords.to_json.html_safe %>
myMap.addMarkers(coords)
console.log("Nearby Coordinates", coords)
$(".event-listing").html("<%= j render 'event' %>")

app/views/events/edit.html.erb
<div class="form-container">
  <div class="row">
    <div class="small-7 small-centered columns">
      <div id="edit-event">
        <div class="edit-title form-styling"><h3>Edit Event</h3></div><br />
        <div class="new-event" class="action">
          <%= render 'edit_form' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<div class="container">
  <div class="row">
    <div class="large-4 columns">
      <div class="content" id="movie-details">
        <%= render 'movie_details' %>
      </div>
      <% if @event.host != current_user %>
        <%= render 'commitments/form' %>
      <% end %>
    </div>

    <div class="large-8 small-12 columns">
      <div id="event-details" class="form-styling">
        <%= render 'event_details' %>
      </div>
    </div>
          
    <div class="large-8 small-12 columns">  
      <div id="comments">     

        <%= form_for([@event.host, @event, @comment], :remote => true) do |f| %>
          <div id="comment-form-errors">
            <%= render :partial => "comment_form_errors" %>
          </div>

          <div class="field">
            <%= f.text_area :content, :size => "35x3", maxlength: 500, placeholder: "Leave a comment...", class: "message" %>
          </div>

          <div class="actions">
            <%= f.submit "Add Comment", id: "edit-button", class: "button tiny" %>
          </div>
        <% end %>

        <div id="comment-list">
          <% unless @EventComments.any? %>
            <p id="empty-comments">Leave a comment!</p>
          <% end %>
          <%= render :partial => "comments" %>
        </div>

      </div> 
    </div> 

  </div>
</div>

<script type="text/javascript">
  $(function() {
    $("#new_comment").on('ajax:beforeSend', function() { // set this code to happen just before the ajax request is made
      $("#submit-comment") // make changes to the submit button
        .val('Saving...') // change the text on the button
        .attr('disabled', 'disabled'); // disable the button
      })
    .on('ajax:complete', function() {
      $("#submit-comment")
      .val('Create Comment')
      .removeAttr('disabled');
    });
  });
</script>

app/views/events/welcome.html.erb
<!-- Testing -->
<div class="background-image"></div>

<div class="front-content">
	<p>Find a movie. Invite your friends. Simple.<br /><br /></p>
	<p>To get started, please login or signup.</p><br /><br />
</div>

<div class="login-signup">
	<div class="row">
		<div class="small-11 medium-6 large-6 small-centered columns">

			<dl class="tabs" data-tab>
				<dd class="active small-6 tab-effects"><a href="#welcome-panel1" class="left-welcome-tab">Login</a></dd>
				<dd class="small-6 tab-effects"><a href="#welcome-panel2" class="right-welcome-tab">Sign Up</a></dd>
			</dl>

			<div class="tabs-content">
				<div class="content active" id="welcome-panel1">
					<%= render 'user_sessions/form' %>
				</div>

				<div class="content" id="welcome-panel2">
				  	<%= render 'users/signup_form' %> 
				</div> 
			</div>
		</div>
	</div>
</div>