config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'welcome' => 'events#welcome'
  root "events#welcome"
  
  resources :users do
    member do
      get :activate
    end
    resources :events, except:[:new, :index] do
      resources :comments, only: [:destroy, :update, :create]
    end
    resources :movie_interests, except: [:index, :show]
    resources :ratings
    resources :commitments, only: [:destroy, :update, :create]
  end
  resources :friendships, only: [:destroy, :create] 
  resources :user_sessions, only: [:destroy, :new, :create]

  get 'all_events' => 'events#all_events', :as => :events
  # get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout
end

app/models/commitment.rb
class Commitment < ActiveRecord::Base
  belongs_to :event
  belongs_to :user

  validate :event_must_be_within_capacity
  
  # Validation medthod that calls the is_available? method from the event model
  # If a guest attempts to make a commitment that will exceed capacity of the event,
  # the validation fails

  def event_must_be_within_capacity
    unless self.event.is_available?(self.party_size)
      errors.add(:party_size, "Overcapacity")
    end
  end

  def guests
    if party_size
      if party_size > 1
        "+ " + (party_size - 1).to_s
      end
    end
  end

end

app/controllers/commitments_controller.rb
class CommitmentsController < ApplicationController
  load_and_authorize_resource
  
  def create
    @commitment = Commitment.new(commitment_params)
    # We can grab user_id and event_id because we passed them into the params
    # in the new commitment form (in the event show page).
    @event = Event.find(params[:event_id])

    @user = current_user
    @host = @event.host

    # Ensuring the instantiated commitment is attributed to the correct event 
    # and the correct user (the current_user)
    @commitment.event_id = @event.id
    @commitment.user_id = @user.id

    if @commitment.save
      redirect_to user_event_path(@host, @event), notice: "POP POP"
    else
      redirect_to user_event_path(@host, @event, commitment_errors: @commitment.errors.messages), notice: "Error joining event, try again!"
    end
  end

  def destroy
    @commitment = Commitment.find(params[:id])
    @commitment.destroy
    redirect_to events_path, notice: "Party Poopr"
  end

  def update
    @commitment = Commitment.find(params[:id])
    @event = Event.find(params[:event_id])
    @commitment.event_id = @event.id
    @commitment.user_id = current_user.id
    @host = @commitment.event.host
    if @commitment.update_attribute(:party_size, commitment_params[:party_size]) 
      redirect_to user_event_path(@host, @commitment.event), notice: "Party size successfully modified!"
    else
      redirect_to user_event_path(@host, @commitment.event), notice: "Error, try again!"
    end
  end
  private
  def commitment_params
    params.require(:commitment).permit(:party_size, :event_id, :user_id) 
  end
end

app/helpers/commitments_helper.rb
module CommitmentsHelper
end

app/views/commitments/_form.html.erb
<!-- In the form_for, we specify the url since we are posting to a controller -->
<!-- other than the one in which we currently are; currently in EVENTS, and   -->
<!-- posting to COMMITMENTS. We also pass into the params the user_id and     -->
<!-- event_id in order to be able to associate the new commitment to the      -->
<!-- correct user and event; the assignment happens in the commitments        -->
<!-- controller create action.                                                -->
<!-- 



 -->

<div id="commit-event">
  <% if @event.host != current_user %>
    <% if @event.attendees.include?(current_user) %> 
      <p><strong>You are attending</strong><%= image_tag "Popcorn.svg", id: "avatar-thumb" %></p>
      <% if @event.commitments.sum(:party_size) == @event.capacity %>
        <p>Event is at capacity</p>
      <% end %>
        <%= form_for([@event, @commitment], url: user_commitment_path(current_user, @commitment, event_id: params[:id])) do |f| %>

        <% if params[:commitment_errors] %>

          <div id="error_explanation">
            <h2><%= pluralize(params[:commitment_errors].count, "error") %> prohibited this commitment from being saved:</h2>

            <ul>
              <% params[:commitment_errors].each do |message| %>
              <li><%= message[1][0] %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <% if @event.commitments.sum(:party_size) != @event.capacity %>
          <div class="field">
            <%= f.label :party_size %>
            <%= f.number_field :party_size, {min: 1, value: @commitment.party_size, max: (@event.capacity - @event.commitments.sum(:party_size) + @commitment.party_size)} %>
          </div>

          <div class="actions">
            <%= f.submit "Update", class: "tiny button"%>
          </div>
        <% end %>  

      <% end %>
      <%= link_to "Cancel", user_commitment_path(current_user, @commitment), method: :delete, id: "cancel-commitment" %>   
    <% else %>
      <% if @event.commitments.sum(:party_size) != @event.capacity %>   
        <%= form_for([@event, @commitment], url: user_commitments_path(user_id: current_user.id, event_id: params[:id])) do |f| %>

        <% if params[:commitment_errors] %>

          <div id="error_explanation">
            <h2><%= pluralize(params[:commitment_errors].count, "error") %> prohibited this commitment from being saved:</h2>

            <ul>
              <% params[:commitment_errors].each do |message| %>
                <li><%= message[1][0] %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="field">
          <h5><strong>Join the Event!</strong></h5>
          <%= f.label :party_size %>
          <%= f.number_field :party_size, {min: 1, max: @event.capacity - @event.commitments.sum(:party_size), value: 1} %>
        </div>

        <div class="actions">
          <%= f.submit "Join!", class: "tiny button"%>
        </div>
        <% end %>
      <% else %>
        <p>Event is full!</p>
      <% end %>
    <% end %>
  <% else %>
    <div class="large-4 columns"></div>
  <% end %>
</div>