config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'welcome' => 'events#welcome'
  root "events#welcome"
  
  resources :users do
    member do
      get :activate
    end
    resources :events, except:[:new, :index] do
      resources :comments, only: [:destroy, :update, :create]
    end
    resources :movie_interests, except: [:index, :show]
    resources :ratings
    resources :commitments, only: [:destroy, :update, :create]
  end
  resources :friendships, only: [:destroy, :create] 
  resources :user_sessions, only: [:destroy, :new, :create]

  get 'all_events' => 'events#all_events', :as => :events
  # get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout
end

app/views/layouts/_flash.html.erb
<% flash.each do |name, msg| %>
  <div class="alert-message info"> 
    <p><%= msg %></p>
  </div>
<% end %>

app/views/layouts/_requests.html.erb
<%= link_to image_tag("friend_request.png", id:"friend-icon"), user_path(current_user), id:"friend-icon"%>

<% if current_user.incoming_friendships.count > 0 %>
	<div id="friend-number">+<%= current_user.incoming_friendships.count %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>Popr</title>
		<%= include_gon %>
		<%= stylesheet_link_tag    'application', media: 'all' %>
		<%= javascript_include_tag 'application' %>
		<%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=#{Rails.application.secrets.google_maps_api}" %>
		<%= javascript_include_tag "vendor/modernizr" %>
		<link href='http://fonts.googleapis.com/css?family=Open+Sans+Condensed:300|Nunito' rel='stylesheet' type='text/css'>
		<link href='http://fonts.googleapis.com/css?family=Arimo|Roboto' rel='stylesheet' type='text/css'>
		<%= csrf_meta_tags %>
		<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
	</head>
	<body data-controller="<%= controller_name %>">	

		<div style="border-bottom">
			<div class="fixed"> 
			<nav class="top-bar" data-topbar role="navigation">
				<ul class="title-area">
					<li class="name">
						<h1 class="top-title"><%= link_to image_tag('popr_logo.png', size:"210x80", class: "popr-logo"), root_path %></a></h1>
					</li>
				<!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
					<li class="toggle-topbar menu-icon">
						<a href="#"><span>Menu</span></a>
					</li>
				</ul>

				<% if current_user %>
					<section class="top-bar-section">
						<!-- Right Nav Section -->
						<ul class="right">

							<li id="friend-request" class="show-for-medium-up">
								<div id="friend-container">
					        		<%= render :partial => "layouts/requests" %>
								</div>
							</li>
							
							<li id="friend-button">
								<%= link_to 'Invite Friends', users_path %>
							</li>

							<li id="event-button"><%= link_to 'Movies', new_user_movie_interest_path(user_id: current_user) %>
							</li>
							
							<li class="has-dropdown">
								<a href="#">
									<% if current_user %>
									<%= image_tag("#{current_user.avatar.thumb}", id: "current-thumb")%> &nbsp;<%= current_user.first_name%>
									<% end %>
								</a>

								<ul class="dropdown">
									<li><%= link_to 'My Profile', user_path(current_user) %></li>
									<li><%= link_to 'My Reviews', user_ratings_path(current_user.id) %></li>
									<li><%= link_to "Logout", logout_path, method: :post %></li>
								</ul>
							</li>	
						</ul>

					</section>
				<% end %>
			</nav>
			</div>
		</div>

		<% unless controller.controller_name == "movie_interests" %>
			<% if (flash[:alert]) %>
				<div class="error-box">
					<p class="alert"><%= flash[:alert] %></p>
				</div>
			<% end %>
			<% if (flash[:notice]) %>
				<div class="success-box">
					<p class="notice"><%= flash[:notice] %></p>
				</div>
			<% end %>
		<% end %>
			<div class="yield-body">
				<%= yield %>
			</div>

			<div class="notification-tab">
				<% if current_user%>
					<div id="incoming-requests">
						<%= render partial: "users/incoming_friendships" %>
					</div>
				<% end %>
			</div> 
			<footer>
				<div id="info-box">
					<!-- <strong>Popr (2015) was developed by:</strong/><br/> -->
					<%= image_tag("p4popr.png", id:"info-img") %>
					<a href="http://abdullahonline.co" target="_blank">Abdullah Pharaon</a><br/>
					<a href="http://www.nhaley.ca" target="_blank">Nicholas Haley</a><br/>
					<a href="http://wduntak.github.io/" target="_blank">Wangdu Duntak</a><br/>
				</div>
				<i id="footer-button" class="fa fa-info-circle"></i>
			</footer>
		</body>
		</html>